### ISSUE TITLE
Mad::Mapper should not be tightly bound to MySQL

### ISSUE THREAD

**Issue by kberov** [jhthorsen/mad-mapper#1]
I intend to use Mad::Mapper not only with Mojo::mysql.
Please replace all occurrences of ```$res->sth->mysql_insertid``` with something like
```$self->dbh->last_insert_id(undef, undef, $self->table, $self->pk)```
I know Mad::Mapper is still new, but it should not be bound to one specific database driver.
Please inform if otherwise.
Thanks.

**Comment by jhthorsen** [comment]
The documentation states:

> Currently the supported backends are Mojo::Pg or Mojo::mysql, both which are optional dependencies.

Are you going to use it with Mojo::SQLite as well...? I haven't tested it with that driver, but I would very much like to support it.

**Comment by kberov** [comment]
Mojo::SQLite,Mojo::Pg and Mojo::mysql are a good start :) and this would cover more than 90% of the use-cases. Mojo::SQLite should (must?!) not be used in asynchronous mode, but I do not know the exact technical details - the internals where the mode is switched.

**Comment by jhthorsen** [comment]
Why can't Mojo::SQLite be used in async mode? I know the database is synchronous, but that doesn't mean that Mojo::SQLite shouldn't support an async API.

Actually, I got @Grinnz to support just that: https://metacpan.org/pod/Mojo::SQLite::Database#query

The "mode" you're referring to is switched inside Mojo::DRIVER::Database. Mad::Mapper does not change the internals of the $dbh. (DRIVER = Pg, mysql, SQLite)

**Comment by kberov** [comment]
Thanks :) :+1:  !

**Comment by jhthorsen** [comment]
You're welcome :smile:
